version: '3.1'
services:

  jenkins:
    image: jenkins-master    
    container_name: jenkins
    user: root
    privileged: true
    restart: always
    volumes:
      - /var/lib/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - JENKINS_HOME=/var/jenkins_home
    - JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djava.io.tmpdir=/var/jenkins_home/tmp"
    - TMP=/var/jenkins_home/tmp
    - TEMP=/var/jenkins_home/tmp
    - TMPDIR=/var/jenkins_home/tmp
    - JENKINS_OPTS="--webroot=/var/cache/$NAME/war --httpPort=$HTTP_PORT --httpListenAddress=127.0.0.1"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"    

  jenkins-slave:
    image: jenkins-slave
    container_name: jenkins-slave
    user: root
    privileged: true
    restart: always
    environment:
    - JENKINS_URL=http://jenkins:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - /home/jenkins:/home/jenkins 
    depends_on:
      - jenkins

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/jenkins.conf:/etc/nginx/conf.d/jenkins.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./self_signed/certs/cert.crt:/cert.crt:ro
      - ./self_signed/certs/key.key:/key.key:ro
    ports:
      - 80:80
      - 443:443 
    depends_on: 
      - jenkins
    links: 
      - jenkins
    command: /bin/bash -c "rm -rf /etc/nginx/conf.d/default* && nginx -g 'daemon off;'"

